// flow-typed signature: 999d2c7f85ff653986e46c511cfbbc3b
// flow-typed version: <<STUB>>/licensor_v^3.1.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'licensor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'licensor' {
  declare module.exports: any;
}
